### ISSUE TITLE
求解，直接用手机按键精灵不会被游戏检测到吗？

### ISSUE THREAD

**Issue by sherry0987** [Using1174/yys#1]
我之前了解到，阴阳师好像有获取手机应用的权限，只要手机里装有热门脚本软件，就会被检测到，鬼使黑就会来信。请问你是不是关闭了这个权限呢？是如何关闭的呢？
PS.谢谢你分享的代码，我是按键精灵的初学者，看了你的代码受益匪浅。

**Comment by Using1174** [comment]
一直都没有看到过阴阳师的权限列表里有获取手机应用的权限要求，不知道你用的是哪个平台的版本，我测试时使用的是Bilibili平台的包，没有限制过权限，也没有收到过鬼使黑的来信。你说的情况好像只有在使用了外挂程序修改游戏数据后才会出现。共勉！

**Comment by Using1174** [comment]
一直都没有看到过阴阳师的权限列表里有获取手机应用的权限要求，不知道你用的是哪个平台的版本，我测试时使用的是Bilibili平台的包，没有限制过权限，也没有收到过鬼使黑的来信。你说的情况好像只有在使用了外挂程序修改游戏数据后才会出现。共勉！

**Comment by sherry0987** [comment]
我也是B站版的，授予阴阳师的其中一项权限是检索正在运行的应用，能检索近期运行的和当前运行的任务的相关信息。而且我一直都是开模拟器玩的，用电脑版按键精灵，最近被封了3次，每次都是没发信直接踢掉账户封的。。百思不得其解。。

**Comment by Using1174** [comment]
理论上，运行在模拟器中的安卓应用程序是无法检测到运行在电脑上的按键精灵软件的，你的情况可能是其他原因造成的。这个项目是运行手机版按键精灵上的，环境不同，所以不太清楚你的原因。
